name: CS100 Project

on:
  push:
    branches: [ master, main, SwayamDani/poker ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Setup GoogleTest
      run: |
        git submodule update --init --recursive
        cmake .
        make

    - name: Run Tests
      run: ./poker_tests